# Generated by Django 5.0.7 on 2024-07-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='persona',
            new_name='User',
        ),
    ]
